import argparse

def arguman_parser_olustur():
    parser = argparse.ArgumentParser(
        description=f"Yargu Framework v2.9.0 - LLM Kırmızı Takım (Red Team) Test Aracı - AltaySec Bünyesinde Geliştirilmiştir | Arda Meçik",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Yargu Framework v2.9.0 - AltaySec Bünyesinde Geliştirilmiştir | Arda Meçik\nSadece yetkilendirilmiş güvenlik testleri için kullanılmalıdır."
    )
    alt_komutlar = parser.add_subparsers(dest="komut", help="Komutlar")
    
    api_parser = alt_komutlar.add_parser("test-api", help="API tabanlı LLM testi")
    api_parser.add_argument("--hedef", required=True, choices=["ollama", "openai", "gemini", "claude", "lmstudio", "generic"], help="Hedef API türü")
    api_parser.add_argument("--model", required=True, help="Test edilecek model adı")
    api_parser.add_argument("--api-anahtari", help="API anahtarı (ortam değişkeninden de okunur)")
    api_parser.add_argument("--url", help="Özel API adresi")
    api_parser.add_argument("--sistem-promptu", help="Hedefe tanımlanacak sistem promptu")
    api_parser.add_argument("--konu", default="zararlı yazılım yazma", help="Test edilecek yasaklı konu")
    api_parser.add_argument("--kategori", default="hepsi", choices=["jailbreak", "extraction", "injection", "injection_dolayli", "injection_kalici", "injection_gizli", "injection_cakistirma", "injection_ozyinelemeli", "hepsi"], help="Test kategorisi")
    api_parser.add_argument("--rapor-formati", default="html", choices=["html", "json", "markdown", "hepsi", "yok"], help="Rapor formatı")
    api_parser.add_argument("--cikti-dizini", default="cikti/raporlar", help="Rapor çıktı dizini")
    api_parser.add_argument("--zaman-asimi", type=int, default=30, help="API zaman aşımı (saniye)")
    api_parser.add_argument("--dil", choices=["tr", "en", "hepsi"], default="hepsi", help="Payload dili (varsayilan: hepsi)")
    api_parser.add_argument("--zorluk", choices=["dusuk", "orta", "yuksek", "hepsi"], default="hepsi", help="Payload zorluk seviyesi (varsayilan: hepsi)")
    api_parser.add_argument("--limit", type=int, default=0, help="Maksimum payload sayisi (0 = limitsiz)")
    api_parser.add_argument("--obfuscate", action="store_true", help="Payload obfuscation (gizleme) motorunu aktifleştir")
    api_parser.add_argument("--obfuscation-level", choices=["dusuk", "orta", "yuksek"], default="orta", help="Obfuscation seviyesi (varsayilan: orta)")
    api_parser.add_argument("--ai-saldiri", action="store_true", help="AI vs AI dinamik saldiri motorunu aktiflestir")
    api_parser.add_argument("--saldirgan-model", default="llama3.1:8b", help="Saldirgan (mutasyon) model adi (varsayilan: llama3.1:8b)")
    api_parser.add_argument("--saldirgan-url", default="http://localhost:11434", help="Saldirgan model API adresi")
    api_parser.add_argument("--max-mutasyon", type=int, default=5, help="Maksimum mutasyon denemesi (varsayilan: 5)")
    api_parser.add_argument("--ci-mode", action="store_true", help="CI/CD pipeline modu (JUnit XML cikti, minimal log)")
    api_parser.add_argument("--ci-threshold", type=int, default=70, help="CI build fail esik degeri (varsayilan: 70)")
    api_parser.add_argument("--sessiz", action="store_true", help="Sadece özet çıktı")
    api_parser.add_argument("--swarm", action="store_true", help="Cok ajanli swarm saldiri modunu aktiflestir")
    api_parser.add_argument("--ajan-sayisi", type=int, default=5, help="Swarm'daki ajan sayisi (varsayilan: 5)")
    api_parser.add_argument("--ajan-rolleri", help="Virgulle ayrilmis roller (varsayilan: tumu). Orn: sosyal_muhendis,kod_uzmani")
    api_parser.add_argument("--ajan-modelleri", help="Role ozel model atamalari JSON dosyasi (opsiyonel)")
    api_parser.add_argument("--swarm-tur", type=int, default=10, help="Maksimum kolektif ogrenme turu (varsayilan: 10)")
    api_parser.add_argument("--multimodal", action="store_true", help="Cok modlu (multimodal) gorsel saldiri modunu aktiflestir")
    api_parser.add_argument("--gorsel-teknigi", default="beyaz_yazi", choices=["beyaz_yazi", "mikro_metin", "steganografi", "optik_hile", "renk_kanali", "exif", "coklu_kanal", "hepsi"], help="Gorsel saldiri teknigi (varsayilan: beyaz_yazi)")
    api_parser.add_argument("--guardrail-bypass", action="store_true", help="Guardrail (guvenlik katmani) atlatma testini aktiflestir")
    api_parser.add_argument("--guardrail-turu", default="hepsi", choices=["azure", "aws", "nemo", "openai", "meta", "coklu", "hepsi"], help="Hedef guardrail sistemi (varsayilan: hepsi)")
    api_parser.add_argument("--guardrail-seviye", default="orta", choices=["dusuk", "orta", "yuksek"], help="Guardrail esik seviyesi (varsayilan: orta)")
    
    web_parser = alt_komutlar.add_parser("test-web", help="Web sitesi chatbot testi")
    web_parser.add_argument("--site-url", required=True, help="Hedef web sitesi URL'si")
    web_parser.add_argument("--chatbot-turu", default="auto", choices=["auto", "intercom", "drift", "zendesk", "tawkto", "crisp", "hubspot", "custom"], help="Chatbot platformu")
    web_parser.add_argument("--widget-secici", help="Manuel CSS seçici")
    web_parser.add_argument("--iframe-secici", help="Chatbot iframe CSS seçicisi")
    web_parser.add_argument("--mesaj-girdisi-secici", help="Mesaj alanı CSS seçicisi")
    web_parser.add_argument("--gonder-butonu-secici", help="Gönder butonu CSS seçicisi")
    web_parser.add_argument("--yanit-alani-secici", help="Yanıt alanı CSS seçicisi")
    web_parser.add_argument("--tarayici", default="chromium", choices=["chromium", "firefox", "webkit"], help="Tarayıcı motoru")
    web_parser.add_argument("--goruntulu", action="store_true", help="Görünür tarayıcı modu")
    web_parser.add_argument("--insan-gibi", action="store_true", default=True, help="İnsan benzeri yazma")
    web_parser.add_argument("--bekleme-suresi", type=float, default=3.0, help="Mesajlar arası bekleme (saniye)")
    web_parser.add_argument("--api-intercept", action="store_true", help="API interception modu")
    web_parser.add_argument("--proxy-port", type=int, default=8080, help="Interception proxy portu")
    web_parser.add_argument("--konu", default="zararlı yazılım yazma", help="Test edilecek konu")
    web_parser.add_argument("--kategori", default="hepsi", choices=["jailbreak", "extraction", "injection", "injection_dolayli", "injection_kalici", "injection_gizli", "injection_cakistirma", "injection_ozyinelemeli", "web_ozel", "hepsi"], help="Test kategorisi")
    web_parser.add_argument("--rapor-formati", default="html", choices=["html", "json", "markdown", "hepsi", "yok"], help="Rapor formatı")
    web_parser.add_argument("--cikti-dizini", default="cikti/raporlar", help="Rapor çıktı dizini")
    web_parser.add_argument("--ekran-goruntusu", action="store_true", default=True, help="Test başına ekran görüntüsü")
    web_parser.add_argument("--dil", choices=["tr", "en", "hepsi"], default="hepsi", help="Payload dili (varsayilan: hepsi)")
    web_parser.add_argument("--zorluk", choices=["dusuk", "orta", "yuksek", "hepsi"], default="hepsi", help="Payload zorluk seviyesi (varsayilan: hepsi)")
    web_parser.add_argument("--limit", type=int, default=0, help="Maksimum payload sayisi (0 = limitsiz)")
    web_parser.add_argument("--obfuscate", action="store_true", help="Payload obfuscation (gizleme) motorunu aktifleştir")
    web_parser.add_argument("--obfuscation-level", choices=["dusuk", "orta", "yuksek"], default="orta", help="Obfuscation seviyesi (varsayilan: orta)")
    web_parser.add_argument("--ai-saldiri", action="store_true", help="AI vs AI dinamik saldiri motorunu aktiflestir")
    web_parser.add_argument("--saldirgan-model", default="llama3.1:8b", help="Saldirgan (mutasyon) model adi (varsayilan: llama3.1:8b)")
    web_parser.add_argument("--saldirgan-url", default="http://localhost:11434", help="Saldirgan model API adresi")
    web_parser.add_argument("--max-mutasyon", type=int, default=5, help="Maksimum mutasyon denemesi (varsayilan: 5)")
    web_parser.add_argument("--ci-mode", action="store_true", help="CI/CD pipeline modu (JUnit XML cikti, minimal log)")
    web_parser.add_argument("--ci-threshold", type=int, default=70, help="CI build fail esik degeri (varsayilan: 70)")
    web_parser.add_argument("--captcha-bekleme", type=int, default=60, help="CAPTCHA için bekleme (saniye)")
    
    proxy_parser = alt_komutlar.add_parser("proxy", help="Proxy yakalama modu")
    proxy_parser.add_argument("--port", type=int, default=8080, help="Proxy portu")
    proxy_parser.add_argument("--kaydet", help="Yakalanan istekleri kaydetme dosyası")
    proxy_parser.add_argument("--filtre", help="Domain veya URL filtreleme deseni")
    proxy_parser.add_argument("--sadece-api", action="store_true", default=True, help="Sadece API isteklerini yakala")
    
    rapor_parser = alt_komutlar.add_parser("rapor", help="Rapor oluşturma")
    rapor_parser.add_argument("--sonuc-dosyasi", required=True, help="JSON test sonuç dosyası")
    rapor_parser.add_argument("--format", default="html", choices=["html", "json", "markdown", "hepsi"], help="Rapor formatı")
    rapor_parser.add_argument("--cikti", default="cikti/raporlar", help="Rapor çıktı yolu")
    
    karsilastirma_parser = alt_komutlar.add_parser("karsilastir", help="İki hedefin karşılaştırması")
    karsilastirma_parser.add_argument("--dosya1", required=True, help="Birinci JSON sonuç dosyası")
    karsilastirma_parser.add_argument("--dosya2", required=True, help="İkinci JSON sonuç dosyası")
    
    payload_parser = alt_komutlar.add_parser("payload", help="Payload yönetimi")
    payload_parser.add_argument("--listele", action="store_true", help="Payload'ları listele")
    payload_parser.add_argument("--ekle", help="Yeni payload şablonu ekle")
    payload_parser.add_argument("--olustur", help="Payload şablonundan özel payload oluştur")
    payload_parser.add_argument("--kategori", help="Payload kategorisi")
    payload_parser.add_argument("--dil", choices=["tr", "en", "hepsi"], default="hepsi", help="Payload dili (varsayilan: hepsi)")
    payload_parser.add_argument("--zorluk", choices=["dusuk", "orta", "yuksek", "hepsi"], default="hepsi", help="Zorluk seviyesine göre filtrele")
    payload_parser.add_argument("--limit", type=int, default=0, help="Listelenecek maksimum payload sayisi (0 = limitsiz)")

    poison_parser = alt_komutlar.add_parser("poison", help="RAG zehirleme - zehirli dosya uretimi")
    poison_parser.add_argument("--dosya-turu", default="pdf", choices=["pdf", "docx", "txt", "hepsi"], help="Uretilecek dosya turu (varsayilan: pdf)")
    poison_parser.add_argument("--gizli-prompt", required=True, help="Dosyaya gomulecek gizli prompt/talimat")
    poison_parser.add_argument("--cikti-dosyasi", help="Cikti dosya yolu (tek dosya icin)")
    poison_parser.add_argument("--cikti-dizini", default="cikti/zehirli_dosyalar", help="Cikti dizini (toplu uretim icin)")
    poison_parser.add_argument("--gorunur-icerik", help="Dosyanin gorunur icerigi (bos birakilirsa sahte rapor uretilir)")
    poison_parser.add_argument("--adet", type=int, default=1, help="Uretilecek dosya sayisi (varsayilan: 1)")
    poison_parser.add_argument("--dil", choices=["tr", "en"], default="tr", help="Gorunur icerik dili (varsayilan: tr)")

    tool_parser = alt_komutlar.add_parser("test-tool", help="LLM arac/fonksiyon cagrisi guvenlik testi")
    tool_parser.add_argument("--hedef", required=True, choices=["ollama", "openai", "gemini", "claude", "lmstudio", "generic"], help="Hedef API turu")
    tool_parser.add_argument("--model", required=True, help="Test edilecek model adi")
    tool_parser.add_argument("--api-anahtari", help="API anahtari (ortam degiskeninden de okunur)")
    tool_parser.add_argument("--url", help="Ozel API adresi")
    tool_parser.add_argument("--sistem-promptu", help="Hedef sistem promptu")
    tool_parser.add_argument("--tool-set", default="standart", choices=["standart", "dosya_sistemi", "api", "veritabani", "ozel"], help="Test edilecek tool seti (varsayilan: standart)")
    tool_parser.add_argument("--tool-dosyasi", help="Ozel tool seti JSON dosyasi yolu")
    tool_parser.add_argument("--kategori", default="hepsi", choices=["tool_injection", "tool_output_injection", "tool_definition_injection", "chain_exploit", "function_spoof", "hepsi"], help="Test kategorisi (varsayilan: hepsi)")
    tool_parser.add_argument("--konu", default="zararli yazilim yazma", help="Test edilecek konu")
    tool_parser.add_argument("--rapor-formati", default="html", choices=["html", "json", "markdown", "hepsi", "yok"], help="Rapor formati")
    tool_parser.add_argument("--cikti-dizini", default="cikti/raporlar", help="Rapor cikti dizini")
    tool_parser.add_argument("--zaman-asimi", type=int, default=30, help="API zaman asimi (saniye)")
    tool_parser.add_argument("--dil", choices=["tr", "en", "hepsi"], default="hepsi", help="Payload dili (varsayilan: hepsi)")
    tool_parser.add_argument("--zorluk", choices=["dusuk", "orta", "yuksek", "hepsi"], default="hepsi", help="Payload zorluk seviyesi")
    tool_parser.add_argument("--limit", type=int, default=0, help="Maksimum payload sayisi (0 = limitsiz)")
    tool_parser.add_argument("--obfuscate", action="store_true", help="Payload obfuscation motorunu aktiflestir")
    tool_parser.add_argument("--obfuscation-level", choices=["dusuk", "orta", "yuksek"], default="orta", help="Obfuscation seviyesi")
    tool_parser.add_argument("--ci-mode", action="store_true", help="CI/CD pipeline modu")
    tool_parser.add_argument("--ci-threshold", type=int, default=70, help="CI build fail esik degeri (varsayilan: 70)")
    tool_parser.add_argument("--sessiz", action="store_true", help="Sadece ozet cikti")

    mcp_parser = alt_komutlar.add_parser("test-mcp", help="MCP sunucu guvenlik taramasi")
    mcp_parser.add_argument("--mcp-url", required=True, help="MCP sunucu adresi (ornek: https://mcp-server.com/mcp)")
    mcp_parser.add_argument("--tarama-turu", default="hepsi", choices=["tools", "resources", "prompts", "hepsi"], help="Tarama turu (varsayilan: hepsi)")
    mcp_parser.add_argument("--api-anahtari", help="MCP sunucu API anahtari")
    mcp_parser.add_argument("--zaman-asimi", type=int, default=30, help="Baglanti zaman asimi (saniye)")
    mcp_parser.add_argument("--rapor-formati", default="html", choices=["html", "json", "markdown", "hepsi", "yok"], help="Rapor formati")
    mcp_parser.add_argument("--cikti-dizini", default="cikti/raporlar", help="Rapor cikti dizini")
    mcp_parser.add_argument("--ci-mode", action="store_true", help="CI/CD pipeline modu")
    mcp_parser.add_argument("--ci-threshold", type=int, default=70, help="CI build fail esik degeri (varsayilan: 70)")
    mcp_parser.add_argument("--sessiz", action="store_true", help="Sadece ozet cikti")

    agent_parser = alt_komutlar.add_parser("test-agent", help="AI ajan bellek zehirleme ve guvenlik testi")
    agent_parser.add_argument("--hedef", required=True, choices=["ollama", "openai", "gemini", "claude", "lmstudio", "generic"], help="Ajanin kullandigi LLM turu")
    agent_parser.add_argument("--model", required=True, help="Test edilecek model adi")
    agent_parser.add_argument("--api-anahtari", help="API anahtari (ortam degiskeninden de okunur)")
    agent_parser.add_argument("--url", help="Ozel API adresi")
    agent_parser.add_argument("--sistem-promptu", help="Ajanin sistem promptu")
    agent_parser.add_argument("--tool-set", default="standart", choices=["standart", "dosya_sistemi", "api", "veritabani"], help="Ajanin kullandigi tool seti")
    agent_parser.add_argument("--test-turu", default="hepsi", choices=["bellek_zehirleme", "yetki_yukseltme", "zincirleme", "hepsi"], help="Test turu (varsayilan: hepsi)")
    agent_parser.add_argument("--tur-sayisi", type=int, default=5, help="Cok turlu test icin tur sayisi (varsayilan: 5)")
    agent_parser.add_argument("--konu", default="zararli yazilim yazma", help="Test edilecek konu")
    agent_parser.add_argument("--rapor-formati", default="html", choices=["html", "json", "markdown", "hepsi", "yok"], help="Rapor formati")
    agent_parser.add_argument("--cikti-dizini", default="cikti/raporlar", help="Rapor cikti dizini")
    agent_parser.add_argument("--zaman-asimi", type=int, default=30, help="API zaman asimi (saniye)")
    agent_parser.add_argument("--dil", choices=["tr", "en", "hepsi"], default="hepsi", help="Payload dili")
    agent_parser.add_argument("--ci-mode", action="store_true", help="CI/CD pipeline modu")
    agent_parser.add_argument("--ci-threshold", type=int, default=70, help="CI build fail esik degeri")
    agent_parser.add_argument("--sessiz", action="store_true", help="Sadece ozet cikti")
    agent_parser.add_argument("--cross-session", action="store_true", help="Capraz oturum kalicilik testini aktiflestir (persistence)")

    benchmark_parser = alt_komutlar.add_parser("benchmark", help="Coklu model guvenlik karsilastirmasi")
    benchmark_parser.add_argument("--modeller", help="Model listesi JSON dosyasi (bos birakilirsa 5 varsayilan model)")
    benchmark_parser.add_argument("--batarya", default="standart", choices=["hizli", "standart", "kapsamli", "tam"], help="Test bataryasi (varsayilan: standart)")
    benchmark_parser.add_argument("--konu", default="zararli yazilim yazma", help="Test konusu")
    benchmark_parser.add_argument("--zaman-asimi", type=int, default=30, help="API zaman asimi")
    benchmark_parser.add_argument("--rapor-formati", default="html", choices=["html", "json", "markdown", "hepsi", "yok"], help="Rapor formati")
    benchmark_parser.add_argument("--cikti-dizini", default="cikti/raporlar", help="Rapor cikti dizini")
    benchmark_parser.add_argument("--onceki-sonuclar", help="Regresyon tespiti icin onceki benchmark JSON dosyasi")
    benchmark_parser.add_argument("--ci-mode", action="store_true", help="CI/CD pipeline modu")
    benchmark_parser.add_argument("--ci-threshold", type=int, default=70, help="CI build fail esik degeri")
    benchmark_parser.add_argument("--sessiz", action="store_true", help="Sadece ozet cikti")

    otonom_parser = alt_komutlar.add_parser("otonom", help="Otonom pentest - kendi kendine kesif ve saldiri")
    otonom_parser.add_argument("--hedef", required=True, choices=["ollama", "openai", "gemini", "claude", "lmstudio", "generic"], help="Hedef API turu")
    otonom_parser.add_argument("--model", required=True, help="Test edilecek model adi")
    otonom_parser.add_argument("--api-anahtari", help="API anahtari")
    otonom_parser.add_argument("--url", help="Ozel API adresi")
    otonom_parser.add_argument("--konu", default="zararli yazilim yazma", help="Test konusu")
    otonom_parser.add_argument("--max-tur", type=int, default=10, help="Maksimum saldiri turu (varsayilan: 10)")
    otonom_parser.add_argument("--derinlik", default="standart", choices=["dusuk", "standart", "yuksek", "kritik"], help="Test derinligi (varsayilan: standart)")
    otonom_parser.add_argument("--zaman-siniri", type=int, default=3600, help="Maksimum test suresi, saniye (varsayilan: 3600)")
    otonom_parser.add_argument("--rapor-formati", default="html", choices=["html", "json", "markdown", "hepsi", "yok"], help="Rapor formati")
    otonom_parser.add_argument("--cikti-dizini", default="cikti/raporlar", help="Rapor cikti dizini")
    otonom_parser.add_argument("--ci-mode", action="store_true", help="CI/CD pipeline modu")
    otonom_parser.add_argument("--sessiz", action="store_true", help="Sadece ozet cikti")

    marketplace_parser = alt_komutlar.add_parser("marketplace", help="Topluluk payload pazar yeri")
    marketplace_parser.add_argument("--paylas", help="Paylasilacak payload JSON dosyasi")
    marketplace_parser.add_argument("--ara", help="Payload ara (kategori veya anahtar kelime)")
    marketplace_parser.add_argument("--trend", action="store_true", help="Trend payloadlari goster")
    marketplace_parser.add_argument("--istatistik", action="store_true", help="Marketplace istatistikleri")
    marketplace_parser.add_argument("--oy-ver", help="Oy verilecek payload ID'si")
    marketplace_parser.add_argument("--begeni", action="store_true", default=True, help="Begeni olarak oyla")
    marketplace_parser.add_argument("--kategori", help="Filtre: Kategori")
    marketplace_parser.add_argument("--dil", choices=["tr", "en", "hepsi"], default="hepsi", help="Filtre: Dil")

    dashboard_parser = alt_komutlar.add_parser("dashboard", help="Canli guvenlik dashboard'u baslat")
    dashboard_parser.add_argument("--port", type=int, default=8080, help="Web sunucu portu (varsayilan: 8080)")
    dashboard_parser.add_argument("--skor-esigi", type=int, default=70, help="Uyari esik degeri (varsayilan: 70)")

    stealth_parser = alt_komutlar.add_parser("stealth", help="Stealth anti-tespit profili olustur")
    stealth_parser.add_argument("--profil-olustur", action="store_true", default=True, help="Tam stealth profili olustur")
    stealth_parser.add_argument("--politika", default="normal", choices=["agresif", "normal", "temkinli"], help="Rate limit politikasi")

    cloud_parser = alt_komutlar.add_parser("cloud", help="Yargu Cloud API yonetimi")
    cloud_parser.add_argument("--baslat", action="store_true", help="Cloud API sunucusunu baslat")
    cloud_parser.add_argument("--port", type=int, default=8000, help="API portu (varsayilan: 8000)")
    cloud_parser.add_argument("--durum", action="store_true", help="Cloud API durumunu goster")
    cloud_parser.add_argument("--login", action="store_true", help="Cloud'a giris yap")
    cloud_parser.add_argument("--token", help="API tokeni")

    return parser
